version: '2'
services:
  redis:
    image: redis

  status_service:
    image: crossref/event-data-status
    expose:
     - "8003"
    ports:
     - "8003:8003"
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    depends_on:
     - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - REDIS_DB=0
     - PORT=8003
     - JWT_SECRETS=TEST,TEST2
    command: "lein run"
